export const CHANGE_TOP_BANNERS = 'GG_CHANGE_TOP_BANNERS';
export const CHANGE_HOT_RECOMMENDS = 'GG_CHANGE_HOT_RECOMMENDS';
export const CHANGE_NEW_ALBUMS = 'GG_CHANGE_NEW_ALGUMS';

export const CHANGE_UP_RANKING = 'GG_CHANGE_UP_RANKING';
export const CHANGE_NEW_RANKING = 'GG_CHANGE_NEW_RANKING';
export const CAHNGE_ORIGIN_RANKING = 'GG_CHANGE_ORIGIN_RANKING';
